export const STUDY_PROGRAMS = [
	"Informatikk: programmering og systemarkitektur",
	"Informatikk: design, bruk og interaksjon",
	"Informatikk: digital økonomi og ledelse",
	"Informatikk: språkteknologi",
	"Informatikk: maskinlæring og kunstig intelligens",
	"Informatikk: robotikk og intelligente systemer",
	"Elektronikk, informatikk og teknologi",
	"Matematikk med informatikk",
	"Informasjonssikkerhet",
	"Computational science",
	"Data science",
	"Entreprenørskap og innovasjonsledelse",
	"Digitalisering i helsesektoren",
	"Informatikk (årsenhet)",
	"IT-arkitektur (årsenhet)",
	"Enkeltemne(r)",
] as const;
