// Company-facing copy for the offer page on Hugin (/bestill-bedpres/tilbud/<token>). The page
// speaks to the company as «dere». Answer rules live in lib/schema/company-offer-schema.ts.

export const COMPANY_OFFER_COPY = {
	loading: "Henter tilbudet …",
	optional: "Valgfritt",
	back: "Tilbake til tilbudet",
	busy: "Sender …",
	facts: {
		type: "Type",
		students: "Studenter",
		upTo: (count: number) => `Opptil ${count}`,
		venue: "Sted",
		terms: "Vilkår",
		termsLink: "Standardvilkår",
	},
	offer: {
		title: (company: string) => `Tilbud til ${company}`,
		held: "Datoen er holdt av til dere",
		termsLabel: "Vi har lest og godtar",
		termsLink: "standardvilkårene",
		termsLabelEnd: "for bedriftsarrangement.",
		/** When the semester has no terms to link to. */
		termsLabelPlain: "Vi godtar vilkårene for bedriftsarrangement.",
		accept: "Godta dato og vilkår",
		accepting: "Godtar …",
		askForNewDate: "Be om en annen dato",
		decline: "Takk nei, vi kan ikke i år",
	},
	newDate: {
		title: "Be om en annen dato",
		lede: "Bedriftskontakten ser ønsket og kommer tilbake med et nytt tilbud.",
		datesLabel: "Hvilke datoer passer bedre?",
		atLimit: (max: number) => `Dere kan velge opptil ${max} datoer.`,
		noDates: "Det er ingen andre datoer å velge her. Skriv til",
		noDatesEnd: ", så finner vi en løsning.",
		commentLabel: "Noe vi bør vite?",
		send: "Send ønsket",
	},
	decline: {
		title: "Takke nei til tilbudet?",
		withdraws: (semester: string) => `Da trekker vi søknaden deres for ${semester}`,
		freesDay: ", og",
		freesDayEnd: "blir ledig for en annen bedrift.",
		welcomeBack: "Dere er velkomne til å søke igjen et annet semester.",
		commentLabel: "Vil dere si hvorfor?",
		send: "Takk nei",
	},
	states: {
		unknownTitle: "Fant ikke tilbudet",
		unknownBody: "Lenken er ikke gyldig. Sjekk at dere har kopiert hele lenken fra e-posten.",
		unknownNote: "Fungerer det fortsatt ikke? Skriv til",
		acceptedTitle: "Dere har godtatt tilbudet",
		acceptedBody: "Takk! Bedriftskontakten ser svaret deres.",
		acceptedAt: (moment: string) => `Godtatt ${moment}`,
		accepted: "Godtatt",
		acceptedNext: "Org-ansvarlig tar kontakt 4–5 uker før arrangementet.",
		newDateTitle: "Vi har fått ønsket deres",
		newDateAskedFor: "Dere ba om",
		newDateBody: "Bedriftskontakten ser ønsket og kommer tilbake med et nytt tilbud.",
		newDateCard: "Dere har bedt om en annen dato",
		newDateDecline: "Vil dere heller takke nei?",
		or: " eller ",
		supersededTitle: "Dere har fått et nyere tilbud",
		supersededBody:
			"Dette tilbudet gjelder ikke lenger. Bruk den nyeste lenken dere har fått fra Navet.",
		supersededNote: "Finner dere ikke lenken? Skriv til",
		supersededNoteEnd: ", så sender vi den på nytt.",
		declinedTitle: "Dere har takket nei",
		declinedBody: (semester: string) =>
			`Takk for at dere sa fra. Datoen er frigitt, og søknaden for ${semester} er trukket. Dere er hjertelig velkomne til å søke igjen et annet semester.`,
		declinedNote: "Ombestemt dere, eller har dere spørsmål? Skriv til",
		inactiveTitle: "Tilbudet gjelder ikke lenger",
		inactiveBody: (company: string, semester: string) =>
			`Søknaden fra ${company} er ikke aktiv for ${semester}.`,
		inactiveNote: "Tror dere dette er feil? Skriv til",
	},
} as const;
