import { ADMISSIONS_GUIDE_STEPS, ADMISSIONS_GUIDE_STORAGE_KEY } from "../admissions";
import { ENGAGEMENT_GUIDE_STEPS, ENGAGEMENT_GUIDE_STORAGE_KEY } from "../engagement/guide";
import {
	EVENT_GUIDE_STEPS,
	EVENT_GUIDE_STORAGE_KEY,
	EVENTS_LIST_GUIDE_STEPS,
	EVENTS_LIST_GUIDE_STORAGE_KEY,
} from "../events/guide";
import { JOB_LISTINGS_GUIDE_STEPS, JOB_LISTINGS_GUIDE_STORAGE_KEY } from "../job-listings";
import { ORGANIZATION_GUIDE_STEPS, ORGANIZATION_GUIDE_STORAGE_KEY } from "../organization";

export const GUIDE_STEPS = {
	[ADMISSIONS_GUIDE_STORAGE_KEY]: ADMISSIONS_GUIDE_STEPS,
	[ENGAGEMENT_GUIDE_STORAGE_KEY]: ENGAGEMENT_GUIDE_STEPS,
	[EVENT_GUIDE_STORAGE_KEY]: EVENT_GUIDE_STEPS,
	[EVENTS_LIST_GUIDE_STORAGE_KEY]: EVENTS_LIST_GUIDE_STEPS,
	[JOB_LISTINGS_GUIDE_STORAGE_KEY]: JOB_LISTINGS_GUIDE_STEPS,
	[ORGANIZATION_GUIDE_STORAGE_KEY]: ORGANIZATION_GUIDE_STEPS,
} as const satisfies Record<string, readonly string[]>;

export type GuideKey = keyof typeof GUIDE_STEPS;

export const GUIDE_KEYS = Object.keys(GUIDE_STEPS) as GuideKey[];
